package com.nexomc.nexo.api.events.resourcepack

import com.nexomc.nexo.api.NexoPack
import com.nexomc.nexo.pack.creative.NexoPackReader
import com.nexomc.nexo.utils.printOnFailure
import org.bukkit.event.Event
import org.bukkit.event.HandlerList
import team.unnamed.creative.ResourcePack
import team.unnamed.creative.base.Writable
import java.io.File

/**
 * Fires after all files are generated by Nexo, but before the pack is obfuscated
 * This is to make you able to easily alter the pack without needing to access uuid-filenames
 */
class NexoPostPackGenerateEvent(val resourcePack: ResourcePack) : Event() {
    fun addResourcePack(resourcePack: ResourcePack): Boolean {
        return runCatching {
            NexoPack.mergePack(this.resourcePack, resourcePack)
        }.printOnFailure().getOrNull() != null
    }

    fun addResourcePack(resourcePack: File): Boolean {
        return runCatching {
            NexoPack.mergePack(this.resourcePack, NexoPackReader().readFile(resourcePack))
        }.printOnFailure().getOrNull() != null
    }

    fun addUnknownFile(path: String, data: ByteArray): Boolean {
        return runCatching {
            this.resourcePack.unknownFile(path, Writable.bytes(data))
        }.printOnFailure().getOrNull() != null
    }

    override fun getHandlers() = handlerList

    companion object {
        @JvmStatic
        val handlerList = HandlerList()
    }
}
